### ISSUE TITLE
[BUG] Galactic war freezes midway through battles

### ISSUE THREAD

**Issue by RagingFlames** [Quitch/GW-AI-Overhaul#93] opened 2023-09-15 17:23 UTC
## Attestation

[x] I have verified this bug with all other mods disabled

[x] I am not using one of the documented [incompatible mods](https://github.com/Quitch/GW-AI-Overhaul#incompatible-mods)

[x ] I have confirmed this happens after [verifying the games files](https://support.planetaryannihilation.com/kb/faq.php?id=188)

[x] I was using the latest [graphics drivers](https://support.planetaryannihilation.com/kb/faq.php?id=218)

## Describe the bug

While playing GW, the game will freeze after a battle has been going on for a dozen or so minutes. The battle will not ever recover from this state. The UI and camera still move but the units don't move.

## To Reproduce

Steps to reproduce the behaviour:

1. Go into Galactic war
2. Initiate any battle
3. Play the game normally, the battle will freeze after ~15 minutes

## Expected behaviour

Game should not freeze

## GWO Info

Taken from the top-right GWO panel:

- Version: 5.51
- Difficulty: Iron
[server-2023-09-15_105747.txt](https://github.com/Quitch/GW-AI-Overhaul/files/12622092/server-2023-09-15_105747.txt)

- Size: Epic
- AI: Queller
- Options: Faction Scaling, System Scaling

## Logs
[PA-2023-09-15_105708.txt](https://github.com/Quitch/GW-AI-Overhaul/files/12622089/PA-2023-09-15_105708.txt)
[server-2023-09-15_105747.txt](https://github.com/Quitch/GW-AI-Overhaul/files/12622092/server-2023-09-15_105747.txt)
[PA-2023-09-15_105708.txt](https://github.com/Quitch/GW-AI-Overhaul/files/12622089/PA-2023-09-15_105708.txt)
[localstore.zip](https://github.com/Quitch/GW-AI-Overhaul/files/12622143/localstore.zip)

**Comment by Quitch** [comment] 2023-10-31 09:43
Duplicate of #79 

This is not a complaint, it's very useful to get all this information, it's simply to keep it all in one thread.

**Closed by Quitch** 2023-10-31 09:43 UTC
Labels: bug
