### ISSUE TITLE
[BUG] Game Freeze

### ISSUE THREAD

**Issue by HudoraX69** [Quitch/GW-AI-Overhaul#94] opened 2023-09-16 18:55 UTC
**Game Pauses Time By Itself**

I only have the overhaul mod enabled with the mods activated by default and those are: Ai Bugfixes And Enhancements
                                                                                                                                              PA Chat
I have confirmed this happens after verifying the games files

I was using the latest graphics drivers

as the title says
the game freezes but i can still interact with the mouse

**Steps to reproduce the behaviour:**
it keeps happening at start of the game exactly around 5-6 minutes (i haven't fast forward the time) 

it started happening 2 updates ago meaning of which: 1 week ago 

**Screenshots:**

![20230916203852_1](https://github.com/Quitch/GW-AI-Overhaul/assets/81614106/68391402-8412-4af9-9f57-d424817f5acc)

**GWO Info**

- Version:5.55.0
- Difficulty:Casual (i know i'm sorry)
- Size:Large
- AI:Titans
- Options:Faction scalling
                System scalling
                Easier start (again i'm sorry)
                
**Additional context:**
my assumptions are that maybe the techcards are causing it ?

**List Of Techcards:**
Complete Bot Tech
Bot Combat Tech
Storage Compression Tech
Intelligence Fabrication Tech
Fabrication Bot Upgrade Tech
Improved Commander Build Arm
Sub Commander-Name:Diremachine
                           -Personality:Uber
Sub Commander Duplication Tech
Efficiency Tech
Artillery Fabrication Tech
Commander Engine Tech
Improved Energy Weapons
Bot Fabrication Tech 
Improved Intelligence Tech 
Sub Commander-Name:XOV (Same As Mine)
                           -Personality:Relentess
Complete Energy Tech
Bot Armor Tech

i also have the artillery commander loadout 
                           

[server-2023-09-16_201627.txt](https://github.com/Quitch/GW-AI-Overhaul/files/12641410/server-2023-09-16_201627.txt)
[PA-2023-09-16_203810.txt](https://github.com/Quitch/GW-AI-Overhaul/files/12641411/PA-2023-09-16_203810.txt)

**Comment by Quitch** [comment] 2023-09-18 15:28
Can you please provide a copy of your data folder - https://support.planetaryannihilation.com/kb/faq.php?id=176

**Comment by HudoraX69** [comment] 2023-09-18 15:58
> Can you please provide a copy of your localstore from the data folder - https://support.planetaryannihilation.com/kb/faq.php?id=176

sure
here you go 
https://drive.google.com/drive/folders/1T2UM0Vx4t_x3ZZkl-eby8I-kRgm7T9Ma?usp=sharing

**Comment by Quitch** [comment] 2023-10-31 09:43
Duplicate of #79 

This is not a complaint, it's very useful to get all this information, it's simply to keep it all in one thread.

**Comment by Quitch** [comment] 2023-10-31 09:44
Apologies, I wasn't able to grab a copy of the file before you removed it. Do you still have it?

**Comment by HudoraX69** [comment] 2023-10-31 12:37
> Apologies, I wasn't able to grab a copy of the file before you removed it. Do you still have it? Can you attach it to the issue?

sorry, sadly no

**Closed** 2023-10-31 12:46 UTC
Labels: bug
